# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YYCategories',:git=>'https://github.com/Jentlezhi/YYCategories.git'
  pod 'Masonry'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'JXCategoryView'
  pod 'JXPagingView/Pager','2.1.2'

end
